### ISSUE TITLE
The option '--environment' is not registered

### ISSUE THREAD

**Issue by kgish** [rwjblue/ember-cli-divshot#14]
When I run the following command:
```bash
$ ember divshot push --environment=development
```
I get the following error message:
```bash
version: 0.1.15
The option '--environment' is not registered with the divshot command. \
Run `ember divshot --help` for a list of supported options.
```
Despite this message, everything seems to deploy successfuly.

**Comment by akshayrawat** [comment]
+1 . At first I thought it wasn't working because of the message, but found this issue which says it does infact.

**Comment by charlatan154** [comment]
i thing by default `ember divshot push` deploys development environment. if you want to deploy to another env user `ember divshot push staging` or `ember divshot push production`

**Comment by kgish** [comment]
Yes I understand that this is the default action. I was just referring to the fact that if you choose to use `--environment=development` which is a legal option the warning message is confusing and makes it look like you made an error.
