### ISSUE TITLE
Error trying to push

### ISSUE THREAD

**Issue by fusion2004** [rwjblue/ember-cli-divshot#15]
Heya, I'm running ember-cli 0.2.5 and io.js 2.0.2 (but I also tested node 0.12.2) and I'm running into this issue when trying to push to divshot:

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn /Users/markoleson/Developer/markoleson/node_modules/ember-cli-divshot/node_modules/divshot-cli/bin/divshot.js ENOENT
    at exports._errnoException (util.js:844:11)
    at Process.ChildProcess._handle.onexit (child_process.js:987:32)
    at onErrorNT (child_process.js:1138:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

It seems to be caused by this line in `lib/commands/divshot.js`:

``` javascript
var command = path.join(__dirname, '..', '..', 'node_modules', 'divshot-cli', 'bin', 'divshot.js');
```

I've fixed it locally by adding two more `'..'` to the `path.join`:

``` javascript
var command = path.join(__dirname, '..', '..', '..', '..', 'node_modules', 'divshot-cli', 'bin', 'divshot.js');
```

**Comment by jalcine** [comment]
Funny, I ran into this issue as well. @fusion2004, are you using `io.js` by any chance or even `nvm`? I'm using both of these.

**Comment by JKGisMe** [comment]
I just switched to nvm and now I'm having this problem. Did you find a fix?

**Comment by rared** [comment]
Hey guys, are you using Sublime Text by any chance? There's an issue for a lot of people, including myself, where the following issue is output...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)

Try restarting Sublime Text and try again. Apparently restarting works as well, but this is obviously the better solution (if it works).

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
