### ISSUE TITLE
Ember-cli-divshot uses API_HOST environment variable?

### ISSUE THREAD

**Issue by johnhamelink** [rwjblue/ember-cli-divshot#16]
Hey there,

We're using [ember-cli-dotenv](https://github.com/fivetanley/ember-cli-dotenv) to customise the API we connect to (I like to use lvh.me whereas others prefer to use pow.cx). We're using the `API_HOST` variable to define these endpoints.

However when we use `ember-cli-divshot`, we're getting an error that looks like this:

```
[john:~/Public/titp/moderation] master(+2/-0)* ± ember divshot push
version: 0.2.5
Built project successfully. Stored in "dist".


Creating build ...
Error: Error: Invalid URI "/api.lvh.me:3000/apps/titp/builds"

[object Object]
[john:~/Public/titp/moderation] master(+2/-0)* 1 ±
```

Modifying the variable to `TITP_API_URL` solves this issue.

It seems like `ember-cli-divshot` is using the `.env` file to  retrieve the `API_HOST` variable. Should this variable be namespaced to divshot (`DIVSHOT_API_HOST`) so as not to cause these kind of conflicts?

**Comment by poteto** [comment]
By sheer chance, this has happened to one of my apps as well.

**Comment by brandonjmckay** [comment]
This was happening to me too.

Changing my config name worked.

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
