### ISSUE TITLE
divshot.json routes for assets

### ISSUE THREAD

**Issue by brandonparsons** [rwjblue/ember-cli-divshot#17]
The current `divshot.json`:

``` javascript
  "routes": {
    "/tests": "tests/index.html",
    "/tests/**": "tests/index.html",
    "/**": "index.html"
  }
```

Excludes a route for assets. Is this right? If I directly visit an asset URL (e.g. `mysite.divshot.io/assets/vendor-abcdefg.css`, I get redirected to the `not-found` route of my ember application.

Would it make sense to put something about assets in here?

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
