### ISSUE TITLE
ember divshot init stalls

### ISSUE THREAD

**Issue by elwayman02** [rwjblue/ember-cli-divshot#20]
I'm trying to launch a new app on divshot. Running `ember divshot push` prompted me to first run `ember divshot init` because I didn't have an existing divshot app. When I ran that command, the cli stalled without much information to go on:

```
Built project successfully. Stored in "dist".
name: (jordan-hawker)
```

It's been sitting at that prompt for at least 10 minutes now, not doing anything.  Any idea what's going on here @rwjblue?

**Comment by elwayman02** [comment]
I've created a fresh Ember-CLI sandbox app that demonstrates this behavior:

https://github.com/elwayman02/divshot-sandbox

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
