### ISSUE TITLE
passing flags to divshot

### ISSUE THREAD

**Issue by csantero** [rwjblue/ember-cli-divshot#7]
It seems that it is not possible to pass flags to the divshot executable, since ember-cli swallows arguments that begin with --. So if I call

```
ember divshot push development --token 12345
```

the only arguments the addon sees are `["push", "development", "12345"]`, causing the command to fail.

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
