### ISSUE TITLE
Being able to use Divshot environment variables

### ISSUE THREAD

**Issue by bakura10** [rwjblue/ember-cli-divshot#8]
Hi,

Divshot supports environment variables (http://docs.divshot.com/guides/environment-variables) which is nice because it allows to specify variables per environments and everything is versioned in Divshot.

However, in local development, Divshot requires the divshot server to be launched to properly fetched environement variables. It would be good if this addon would automatically launch the divshot server when "ember server" is launched.

**Comment by rwjblue** [comment]
Divshot has been gone for a long time now, I'm going to go ahead and close this (and will be archiving the repo soon).
